actions:
  vundle: vim +VundleClean! +VundleInstall +VundleInstall! +qall
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    actions:
    - vundle
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_oh-my-zsh:
    src: oh-my-zsh
    dst: ~/.oh-my-zsh
  d_emacs.d:
    src: emacs.d
    dst: ~/.emacs.d
  d_doom.d:
    src: doom.d
    dst: ~/.doom.d
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
profiles:
  base:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - d_oh-my-zsh
    - d_emacs.d
    - d_doom.d
    - f_config.fish
