# Kitty config file

# Preferred color scheme
color0 #000000
color8 #555555
color1 #ff0000
color9 #ff0000
color2  #00ff00
color10 #00ff00
color3  #ffff00
color11 #ffff00
color4  #5555ff
color12 #5555ff
color5  #ff00ff
color13 #ff00ff
color6  #00ffff
color14 #00ffff
color7  #ffffff
color15 #ffffff

# For some reason kitty likes using "xterm-kitty" as TERM (this breaks a lot of stuff) so let's set this to xterm
term xterm